export enum WebhookTopicEnum {
  APP_UNINSTALLED = "APP_UNINSTALLED",

  SHOP_UPDATE = "SHOP_UPDATE",

  PRODUCTS_UPDATE = "PRODUCTS_UPDATE",
  PRODUCTS_DELETE = "PRODUCTS_DELETE",

  CUSTOMERS_DATA_REQUEST = "CUSTOMERS_DATA_REQUEST",
  CUSTOMERS_REDACT = "CUSTOMERS_REDACT",

  SHOP_REDACT = "SHOP_REDACT",
}
